
Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |v|
		v.memory = 3072
		v.cpus = 2
	end
	config.vm.box = "ubuntu-14.04-64"
	config.vm.box_url = "https://github.com/jose-lpa/packer-ubuntu_14.04/releases/download/v2.0/ubuntu-14.04.box"
	config.vm.network :private_network, ip: "192.168.66.99"
	config.vm.provision :shell, :path => "setup-users.sh"
	config.vm.provision :shell, :path => "install-docker.sh"
	config.vm.provision :shell, :path => "config-swap.sh", privileged: true
	config.vm.provision :file, source: "wso2-suite", destination: "/home/vagrant/wso2-suite"
	config.vm.provision :shell, :path => "prepare-wso2-suite.sh"
	config.vm.provision :shell, :path => "install-wso2-am.sh"
	config.vm.provision :shell, :path => "install-wso2-das.sh"
	config.vm.provision :shell, :path => "install-wso2-dss.sh"
	config.vm.provision :shell, :path => "install-wso2-esb.sh"
	config.vm.provision :shell, :path => "install-wso2-is.sh"
	config.vm.provision :shell, :inline => "rm -rf wso2-suite"

end

